name: Deploy Portofolio to Github Pages

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            # Set Git User Identity
            - name: Set Git User Identity
              run: |
                  git config --local user.email "ignatiusodi@gmail.com"
                  git config --local user.name "Ignatius Odi"

            # Install dependencies, Build and Deploy Project
            - name: Install Dependencies, Build and Deploy Project
              run: |
                  npm ci
                  npm run build
                  npm run deploy
